# Generated by Django 3.0.5 on 2020-06-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='success_stories',
            name='image',
            field=models.ImageField(default=None, upload_to='crime/'),
        ),
    ]
