# Generated by Django 3.0.5 on 2020-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0002_success_stories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createagent',
            name='image',
            field=models.ImageField(default=None, upload_to='agent/'),
        ),
    ]
