# Generated by Django 3.0.5 on 2020-06-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0004_auto_20200608_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success_stories',
            name='image',
            field=models.ImageField(default=None, upload_to='crime_story/'),
        ),
    ]
