# Generated by Django 3.0.5 on 2020-06-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0005_auto_20200608_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('Usernmae', models.CharField(max_length=30)),
                ('Contact', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
