# Generated by Django 3.0.5 on 2020-06-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0006_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Usernmae',
            new_name='Username',
        ),
    ]
