# Generated by Django 3.0.5 on 2020-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0008_auto_20200611_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
