# Generated by Django 3.0.5 on 2020-06-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0009_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='department',
            field=models.CharField(default='Defence', max_length=20),
        ),
    ]
