# Generated by Django 3.0.5 on 2020-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0010_adminlogin_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='id',
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='idno',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
