# Generated by Django 3.0.5 on 2020-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0011_auto_20200612_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlogin',
            name='idno',
        ),
        migrations.AddField(
            model_name='adminlogin',
            name='id',
            field=models.IntegerField(default='1', primary_key=True, serialize=False),
        ),
    ]
