# Generated by Django 3.0.5 on 2020-06-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0013_adminlogin_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecreation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='createagent',
            name='id',
        ),
        migrations.AddField(
            model_name='casecreation',
            name='case_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='createagent',
            name='CaseCreation_Agent',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_cybernatics_protetor.CaseCreation'),
        ),
        migrations.AddField(
            model_name='createagent',
            name='agent_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
