# Generated by Django 3.0.5 on 2020-06-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0014_auto_20200613_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='casecreation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
