# Generated by Django 3.0.5 on 2020-06-14 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0015_casecreation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createagent',
            name='CaseCreation_Agent',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='app_cybernatics_protetor.CaseCreation'),
        ),
    ]
