# Generated by Django 3.0.5 on 2020-06-14 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0016_auto_20200614_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign_agent',
            name='Agent_Name',
        ),
        migrations.RemoveField(
            model_name='assign_agent',
            name='case_id',
        ),
        migrations.RemoveField(
            model_name='createagent',
            name='CaseCreation_Agent',
        ),
        migrations.AddField(
            model_name='assign_agent',
            name='CaseCreation_Agent',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='app_cybernatics_protetor.CaseCreation'),
        ),
    ]
