# Generated by Django 3.0.5 on 2020-06-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0019_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='createagent',
            name='Email',
            field=models.EmailField(default=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='createagent',
            name='Contact_Number',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
