# Generated by Django 3.1.1 on 2021-11-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cybernatics_protetor', '0020_auto_20200625_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casecreation',
            name='case_details',
        ),
        migrations.RemoveField(
            model_name='casecreation',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='casecreation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='casedetails',
            name='evidence',
        ),
        migrations.RemoveField(
            model_name='casedetails',
            name='image',
        ),
    ]
